services:
  broker:
    build:
      context: ./Broker
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: broker

  loadbalancer:
    build:
      context: ./LoadBalance
      dockerfile: Dockerfile
    ports:
      - ${LOAD_BALANCE_PORT}:${LOAD_BALANCE_PORT}
    container_name: loadbalancer
    env_file:
      - .env

  server1:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    container_name: server1
    environment:
      - SERVER_HOST=server1
      - SERVER_PORT=1234
      - SPRING_PROFILES_ACTIVE=deploy
    depends_on:
      - broker
      - loadbalancer
         
  server2:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "1235:1235"
    container_name: server2
    environment:
      - SERVER_HOST=server2
      - SERVER_PORT=1235
      - SPRING_PROFILES_ACTIVE=deploy
    depends_on:
      - broker
      - loadbalancer