services:
  broker:
    build:
      context: ./Broker
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: broker

  loadbalancer:
    build:
      context: ./LoadBalance
      dockerfile: Dockerfile
    ports:
      - ${LOAD_BALANCE_PORT}:${LOAD_BALANCE_PORT}
    container_name: loadbalancer
    env_file:
      - .env
