services:
  broker:
    build:
      context: ./Broker
      dockerfile: Dockerfile
    ports:
      - ${MESSAGE_BROKER}:${MESSAGE_BROKER}
    container_name: broker

  loadbalancer:
    build:
      context: ./LoadBalance
      dockerfile: Dockerfile
    ports:
      - ${LOAD_BALANCE_PORT}:${LOAD_BALANCE_PORT}
    container_name: loadbalancer
    env_file:
      - .env

  server1:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - {SERVER_PORT_01}:{SERVER_PORT_01}
    container_name: server1
    environment:
      - SERVER_HOST=server1
      - SERVER_PORT={SERVER_PORT_01}
      - SPRING_PROFILES_ACTIVE=deploy
    depends_on:
      - broker
      - loadbalancer
         
  server2:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - {SERVER_PORT_02}:{SERVER_PORT_02}
    container_name: server2
    environment:
      - SERVER_HOST=server2
      - SERVER_PORT={SERVER_PORT_02}
      - SPRING_PROFILES_ACTIVE=deploy
    depends_on:
      - broker
      - loadbalancer