services:
  broker:
    build:
      context: ./Broker
      dockerfile: Dockerfile
    ports:
      - ${BROKER_PORT}:${BROKER_PORT}
    container_name: broker
    env_file:
      - .env

  loadbalancer:
    build:
      context: ./LoadBalance
      dockerfile: Dockerfile
    ports:
      - ${LOAD_BALANCE_PORT}:${LOAD_BALANCE_PORT}
    container_name: loadbalancer
    env_file:
      - .env
